## 00. PyTorch Fudamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cpu


## Introduction to Tensors
### Creating tensors
PyTorch tensors are created using `torch.Tensor()`
Anytime you encode data into numbers it must be of a Tensor datatype!

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# How many dimensions it has(square bracket pairs)
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
# Total of elems
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
# We have one 3x3 tensor
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [17]:
TENSOR2 = torch.tensor([[[[1,2,4],
           [3,4,5]]]])
TENSOR2

tensor([[[[1, 2, 4],
          [3, 4, 5]]]])

In [18]:
TENSOR2.ndim

4

In [19]:
# Outter most brackets contains one 2x3 tensor
# Next brackets contains again one 2x3 tensor
# Next brackets contains 2 rows of tensors
# Finally the innermost brackets contains 3 cols of tensors
TENSOR2.shape

torch.Size([1, 1, 2, 3])

### Random tensors
Why random tensors?
Random tensors are important because the way that many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> updte random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6405, 0.1735, 0.5680, 0.0733],
        [0.7349, 0.9180, 0.4907, 0.1133],
        [0.5425, 0.3743, 0.2627, 0.8705]])

In [21]:
random_tensor.ndim

2

In [22]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224,224)) # color channels (R,G,B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [23]:
my_random_image_tensor = torch.rand(size=(4, 50,50))
my_random_image_tensor.ndim, my_random_image_tensor.shape, my_random_image_tensor

(3,
 torch.Size([4, 50, 50]),
 tensor([[[2.5657e-01, 6.1542e-01, 9.9721e-01,  ..., 8.1395e-01,
           8.7098e-01, 9.2696e-02],
          [2.7416e-01, 9.1697e-01, 2.7167e-01,  ..., 8.0231e-01,
           6.4590e-01, 3.4780e-01],
          [3.7524e-01, 1.0303e-01, 4.6288e-03,  ..., 3.3278e-01,
           4.4987e-01, 2.7711e-02],
          ...,
          [6.5456e-01, 3.8519e-01, 7.6570e-01,  ..., 3.2600e-01,
           2.9469e-04, 2.7112e-01],
          [7.2261e-01, 2.0542e-01, 3.8520e-01,  ..., 2.4004e-01,
           6.1724e-02, 1.1945e-01],
          [9.1862e-01, 2.7336e-01, 9.7082e-01,  ..., 9.9803e-02,
           6.9967e-01, 2.2175e-01]],
 
         [[1.5633e-01, 4.8214e-01, 9.0465e-01,  ..., 2.6480e-01,
           6.4697e-03, 2.4491e-01],
          [7.1229e-01, 2.3703e-01, 5.9574e-01,  ..., 9.5581e-01,
           6.0648e-01, 9.4119e-01],
          [1.4933e-01, 1.3117e-01, 4.0312e-01,  ..., 9.1237e-01,
           3.2026e-01, 3.6421e-01],
          ...,
          [7.6669e-01, 3.811

### Zeros and ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensors of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [28]:
# Use torch.range()
one_to_ten = torch.arange(start=0,end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors like (something else)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
two_to_eight = torch.arange(start=2, end=9, step=1)
two_to_eight

tensor([2, 3, 4, 5, 6, 7, 8])

In [31]:
eight_zeros = torch.zeros_like(input=two_to_eight)
eight_zeros

tensor([0, 0, 0, 0, 0, 0, 0])

### Tensor datatype
Data types - https://pytorch.org/docs/stable/tensors.html

**Note:** Tensor datatypes is one of the 3 biggest errors you'll run into with PyTorch in deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor (e.g float32, float16 -- how much detaol a single number stores in memory)
                               device=None, # What device is your tensor runs on (e.g cuda, cpu) 
                               requires_grad=False) # Whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get a device from a tensor, can use `tensor.device`

In [38]:
# Create a tensor
some_tensor = torch.tensor(torch.rand(3,4), dtype=torch.float16)
some_tensor

C:\Users\Jennifer\AppData\Local\Temp\ipykernel_14232\2877257096.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  some_tensor = torch.tensor(torch.rand(3,4), dtype=torch.float16)


tensor([[0.6123, 0.7065, 0.6519, 0.7192],
        [0.2964, 0.0459, 0.2065, 0.5552],
        [0.1901, 0.4756, 0.5947, 0.7119]], dtype=torch.float16)

In [39]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')



tensor([[0.6123, 0.7065, 0.6519, 0.7192],
        [0.2964, 0.0459, 0.2065, 0.5552],
        [0.1901, 0.4756, 0.5947, 0.7119]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor opertations include
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [40]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
# Subtract 10 
tensor - 10

tensor([-9, -8, -7])

In [44]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [45]:
torch.add(tensor,10)

tensor([11, 12, 13])

## Matrix multiplication

Two main ways of performing multiplication in neural networs and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matric multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outter dimensions**:
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`

In [46]:
# torch.matmul(torch.rand(3,2), torch.rand(3,2))
torch.matmul(torch.rand(3,2), torch.rand(2,3))


tensor([[1.2969, 1.5719, 0.7224],
        [0.4111, 0.6007, 0.3599],
        [0.9756, 0.9973, 0.3065]])

In [47]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [48]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
tensor

tensor([1, 2, 3])

In [50]:
# Matrix mul. by hand
1*1 + 2*2 + 3*3

14

In [51]:
tensor @ tensor

tensor(14)

In [52]:
%%time
value = 0
for i in range(len(tensor)):
    value+= tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: total: 46.9 ms
Wall time: 4.12 ms


In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

## 

### One of the most common errors in deep learning: shape errors

In [54]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul)
# torch.matmul(tensor_A, tensor_B)


In [55]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [56]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [57]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [58]:
# The matrix multiplcation operation works when tensor_B is transposed
print(f"Original shapes: tensor_A= {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"\nOutput:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A= torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
