## 00. PyTorch Fudamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors
### Creating tensors
PyTorch tensors are created using `torch.Tensor()`
Anytime you encode data into numbers it must be of a Tensor datatype!

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# How many dimensions it has(square bracket pairs)
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
# Total of elems
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
# We have one 3x3 tensor
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [17]:
TENSOR2 = torch.tensor([[[[1,2,4],
           [3,4,5]]]])
TENSOR2

tensor([[[[1, 2, 4],
          [3, 4, 5]]]])

In [18]:
TENSOR2.ndim

4

In [19]:
# Outter most brackets contains one 2x3 tensor
# Next brackets contains again one 2x3 tensor
# Next brackets contains 2 rows of tensors
# Finally the innermost brackets contains 3 cols of tensors
TENSOR2.shape

torch.Size([1, 1, 2, 3])

### Random tensors
Why random tensors?
Random tensors are important because the way that many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> updte random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9043, 0.3142, 0.7821, 0.2410],
        [0.5593, 0.2590, 0.6872, 0.3418],
        [0.0097, 0.7163, 0.7166, 0.1004]])

In [21]:
random_tensor.ndim

2

In [22]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224,224)) # color channels (R,G,B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [23]:
my_random_image_tensor = torch.rand(size=(4, 50,50))
my_random_image_tensor.ndim, my_random_image_tensor.shape, my_random_image_tensor

(3,
 torch.Size([4, 50, 50]),
 tensor([[[0.1387, 0.9072, 0.1042,  ..., 0.9372, 0.3347, 0.8219],
          [0.1954, 0.1579, 0.6042,  ..., 0.0677, 0.7533, 0.0449],
          [0.0728, 0.4328, 0.4508,  ..., 0.2538, 0.4668, 0.6847],
          ...,
          [0.2787, 0.7155, 0.4384,  ..., 0.7126, 0.7655, 0.0292],
          [0.5928, 0.9237, 0.5456,  ..., 0.6272, 0.7472, 0.4244],
          [0.2509, 0.3451, 0.8416,  ..., 0.2734, 0.5628, 0.1819]],
 
         [[0.0147, 0.1760, 0.6249,  ..., 0.1948, 0.0353, 0.2182],
          [0.2231, 0.2109, 0.0204,  ..., 0.8693, 0.2813, 0.1619],
          [0.5675, 0.2782, 0.5537,  ..., 0.6475, 0.2754, 0.6297],
          ...,
          [0.7950, 0.8523, 0.1139,  ..., 0.2303, 0.3323, 0.8174],
          [0.1371, 0.5898, 0.7128,  ..., 0.6496, 0.8269, 0.3710],
          [0.1332, 0.4948, 0.0728,  ..., 0.0697, 0.9864, 0.8643]],
 
         [[0.4558, 0.0279, 0.2035,  ..., 0.2886, 0.1001, 0.2243],
          [0.3210, 0.4316, 0.9214,  ..., 0.0089, 0.9366, 0.5686],
          

### Zeros and ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensors of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [28]:
# Use torch.range()
one_to_ten = torch.arange(start=0,end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors like (something else)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
two_to_eight = torch.arange(start=2, end=9, step=1)
two_to_eight

tensor([2, 3, 4, 5, 6, 7, 8])

In [31]:
eight_zeros = torch.zeros_like(input=two_to_eight)
eight_zeros

tensor([0, 0, 0, 0, 0, 0, 0])

### Tensor datatype
Data types - https://pytorch.org/docs/stable/tensors.html

**Note:** Tensor datatypes is one of the 3 biggest errors you'll run into with PyTorch in deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor (e.g float32, float16 -- how much detaol a single number stores in memory)
                               device=None, # What device is your tensor runs on (e.g cuda, cpu) 
                               requires_grad=False) # Whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get a device from a tensor, can use `tensor.device`

In [38]:
# Create a tensor
some_tensor = torch.tensor(torch.rand(3,4), dtype=torch.float16)
some_tensor

/tmp/ipykernel_14949/2877257096.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  some_tensor = torch.tensor(torch.rand(3,4), dtype=torch.float16)


tensor([[0.8994, 0.7744, 0.2489, 0.3110],
        [0.2686, 0.0414, 0.8667, 0.2842],
        [0.8730, 0.3582, 0.8184, 0.4250]], dtype=torch.float16)

In [39]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')



tensor([[0.8994, 0.7744, 0.2489, 0.3110],
        [0.2686, 0.0414, 0.8667, 0.2842],
        [0.8730, 0.3582, 0.8184, 0.4250]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor opertations include
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [40]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
# Subtract 10 
tensor - 10

tensor([-9, -8, -7])

In [44]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [45]:
torch.add(tensor,10)

tensor([11, 12, 13])

## Matrix multiplication

Two main ways of performing multiplication in neural networs and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matric multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outter dimensions**:
* `(2,3) @ (3,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`

In [46]:
# torch.matmul(torch.rand(3,2), torch.rand(3,2))
torch.matmul(torch.rand(3,2), torch.rand(2,3))


tensor([[0.6247, 0.3358, 0.0912],
        [0.5452, 0.6313, 0.1771],
        [0.8096, 0.7791, 0.2174]])

In [47]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [48]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
tensor

tensor([1, 2, 3])

In [50]:
# Matrix mul. by hand
1*1 + 2*2 + 3*3

14

In [51]:
tensor @ tensor

tensor(14)

In [52]:
%%time
value = 0
for i in range(len(tensor)):
    value+= tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 1.27 ms, sys: 216 µs, total: 1.48 ms
Wall time: 1.01 ms


In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 223 µs, sys: 0 ns, total: 223 µs
Wall time: 186 µs


tensor(14)

## 

### One of the most common errors in deep learning: shape errors

In [54]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul)
# torch.matmul(tensor_A, tensor_B)


In [55]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [56]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [57]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [58]:
# The matrix multiplcation operation works when tensor_B is transposed
print(f"Original shapes: tensor_A= {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"\nOutput:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A= torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Finding the min, max, mean, sum, etc (tensor aggregation) 

In [62]:
# Create a tensor 
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [63]:
# Find the min
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [68]:
# Find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean

(tensor(45.), <function Tensor.mean>)

In [69]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [74]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of minimum value occurs
x.argmin()

tensor(0)

In [75]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a define shape
* View - Return a view of an input tensor of certian shape but keep the same memort as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze -remove all `1` dimensions from a tensor
* Unqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped)
 in a certian way

In [92]:
# Let's create a tensor
import torch
x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [93]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [96]:
# Change the view
z = x.view(1,9) 
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [99]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [105]:
# Stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [111]:
# torch.squeeze() removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shapeL: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shapeL: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [112]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze_(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [115]:
# torch.premute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, color channels]

# Permute the original tensor to rearrange the axis(or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [117]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [119]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [121]:
# Let's index on our new tensor
x[0] # 0th dim

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [124]:
# Let's index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [128]:
# Let's index on the most inner bracket (last dim)
x[0][1][1] #5
x[0][2][2] #9

tensor(9)

In [129]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [130]:
# Get all values of 0th and 1st dim but only index 1 of the 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [131]:
# Get all values of the 0 dim but only 1 index value of the 1st and 2nd dim
x[:,1,1]

tensor([5])

In [132]:
# Get index 0 of the oth and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [146]:
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [162]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch refelcts numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [163]:
# Change the value of the array, what will this do to `tensor`?
array = array + 1
array, tensor 

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [169]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [174]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random number to try and make them better representaions of the data -> agian -> again -> again`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.
Essentially what the random seed does is "flavour" the randomness


In [182]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3612, 0.0068, 0.1712, 0.8723],
        [0.4490, 0.1408, 0.9841, 0.3494],
        [0.3600, 0.9528, 0.6076, 0.4876]])
tensor([[0.3954, 0.4927, 0.6560, 0.1343],
        [0.3264, 0.9742, 0.3711, 0.0440],
        [0.7079, 0.5816, 0.5338, 0.0084]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [189]:
# Let's make some random but reproducible tensors
import torch

# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducability:

* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NIVIDA hardware + Pytorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires purchasing a GPU, there's lots of options... see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this,refer to PyTorch setup docuementation: https://pytorch.org/get-started/locally/

### 2. Check for GPU access with PyTorch

In [193]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [196]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [197]:
# Count number of devices (GPUs)
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [198]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor is not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [199]:
# Move tensor to GPU  (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [202]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()

In [203]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])